### ISSUE TITLE
Need help on training syntax

### ISSUE THREAD

**Issue by mosynaq** [ufal/udpipe#64] opened 2018-03-11 13:52 UTC
Hi everyone. I'm trying to train a model using `udpipe` and I issue the following command:
```bash
../udpipe \
--train \
'modell.udpipe' \
< 'train.conllu' \
--tokenizer 'epochs=60;early_stopping=1;allow_spaces=1' \
--tagger 'templates=tagger' \
--parser 'single_root=0;iterations=20;early_stopping=1;embedding_form_file=fa.word2vec' \
--heldout dev.conllu
```
Tokenization finishes without any problem. But when it comes to tagger, it just occupies a huge part of RAM and does nothing, no matter what I do.
What is my problem? Is it the syntax of the command? Should I provide something?

Thanks!

p.s.
The word2vec model is made using [gensim](https://radimrehurek.com/gensim/), though I'm not sure it is the problem.

**Comment by foxik** [comment] 2018-03-16 22:20
The syntax seem fine. How long did the tagger do nothing? What data are you training to train on? What is the size of the data? How many unique UPOS/XPOS/FEATS tags does it have?

**Comment by mosynaq** [comment] 2018-04-11 16:02
Hey @foxik , thank you for answering! It was looking idle for more than half a day! The size of the data is about 35 MB and it is the Persian portion of [Hamledt3](https://ufal.mff.cuni.cz/hamledt/hamledt-3-treebanks).

**Comment by foxik** [comment] 2018-04-13 11:50
Ok -- the problem is that there are 51105 unique XPOS tags in the data, which of course makes training extremely slow. The problem is that sentence IDs are part of XPOS tags.

For the training to progress, you should either not train on XPOS tags at all (by providing `use_xpostag=0` option for `tagger` argument), or remove the senIDs (`sed 's/|senID=[0-9]*//'); in both cases, the training progresses normally (an iteration per minute or so).

**Comment by foxik** [comment] 2018-05-29 13:06
Closing.

**Closed by foxik** 2018-05-29 13:06 UTC
