### ISSUE TITLE
feature_sequences_score assertion

### ISSUE THREAD

**Issue by GPPassos** [ufal/udpipe#45] opened 2017-09-28 15:16 UTC
I'm trying to train a POS tagger using UDPipe from data which is already in CoNLL format, but not lemmatized. I'm using custom tagsets as well.

However, when reaching iteration 10, an assertion error happens in feature_sequences_optimizer.h.
Here are the logs:

```
Loading training data: done.
Training the UDPipe model.
Tagger model 1 columns: lemma use=0/provide=0, xpostag use=0/provide=0, feats use=0/provide=0
Creating morphological dictionary for tagger model 1.
Tagger model 1 dictionary options: max_form_analyses=0, custom dictionary_file=none
Tagger model 1 guesser options: suffix_rules=8, prefixes_max=0, prefix_min_count=10, enrich_dictionary=6
Tagger model 1 options: iterations=30, early_stopping=1, templates=tagger
Training tagger model 1.
Iteration 1: done, accuracy 74.91%, heldout accuracy 78.47%t/98.35%l/77.87%b
Iteration 2: done, accuracy 78.81%, heldout accuracy 78.32%t/98.49%l/77.80%b
Iteration 3: done, accuracy 79.94%, heldout accuracy 78.02%t/98.57%l/77.56%b
Iteration 4: done, accuracy 80.45%, heldout accuracy 77.78%t/98.58%l/77.34%b
Iteration 5: done, accuracy 80.74%, heldout accuracy 77.57%t/98.61%l/77.14%b
Iteration 6: done, accuracy 80.92%, heldout accuracy 77.33%t/98.62%l/76.91%b
Iteration 7: done, accuracy 81.06%, heldout accuracy 77.21%t/98.61%l/76.78%b
Iteration 8: done, accuracy 81.14%, heldout accuracy 77.15%t/98.61%l/76.72%b
Iteration 9: done, accuracy 81.18%, heldout accuracy 76.98%t/98.59%l/76.55%b
Iteration 10: done, accuracy 81.19%udpipe: ./morphodita/tagger/feature_sequences_optimizer.h:132: ufal::udpipe::morphodita::feature_sequences_optimizer<FeatureSequences<ElementaryFeatures<ufal::udpipe::morphodita::training_elementary_feature_map>, ufal::udpipe::morphodita::training_feature_sequence_map> >::optimize(const original_feature_sequences&, ufal::udpipe::morphodita::feature_sequences_optimizer<FeatureSequences<ElementaryFeatures<ufal::udpipe::morphodita::training_elementary_feature_map>, ufal::udpipe::morphodita::training_feature_sequence_map> >::optimized_feature_sequences&)::<lambda(ufal::udpipe::utils::binary_encoder&, const ufal::udpipe::morphodita::training_feature_sequence_map::info&)> [with FeatureSequences = ufal::udpipe::morphodita::feature_sequences; ElementaryFeatures = ufal::udpipe::morphodita::conllu_elementary_features]: Assertion `feature_sequence_score(info.gamma) == info.gamma' failed.
```

Am I doing anything wrong?

**Comment by foxik** [comment] 2017-09-28 17:34
You are not doing anything wrong. But I have not seen a problem even if training several hundreds of models in 50+ languages.

The assertion means the gamma value computed by the averaged perceptron algorithm in the tagger overflows int32_t -- it is not obvious why it should happen, it may be connected to the fact that you have no lemmas and custom tagset. Can you share the data?

**Comment by GPPassos** [comment] 2017-09-28 20:22
Thank you for your reply. This is indeed surprising.

I'm using this data: https://github.com/GPPassos/macmorpho-UD/tree/experiment (branch: experiment)
For `i`in `{keep-pcp,remove-pcp}`, I'm using `macmorpho-v1-train-$i.conllu` as training data and `macmorpho-v1-dev-$i.conllu` as holdout.

The scripts I'm using for training are at the `/docker-training/` folder.

**Comment by foxik** [comment] 2017-10-09 09:11
Sorry, I am on a research stay abroad and have a family on visit, so I am slacking off. I still plan to look into this, but not right now.

**Comment by fcbr** [comment] 2017-10-26 10:16
We tried to run the training using `udpipe` without any optimization (i.e., debug mode) and still get the crash around iteration 9-10.

**Comment by svetlana21** [comment] 2019-11-20 04:45
The same problem at iteration 19. But I do have lemmas ans standard UD tagset

**Comment by foxik** [comment] 2019-11-24 13:42
OK, the problem is that for non-standard or large data (we normally train on at most ~200MB UD file), the tagger weights can overflow 32bits. You can of course take the model just before the iteration where the overflow occurs; I could also try rescaling gammas (what overflow are the gammas from averaged perceptron) in case they overflow (dividing them by enough large constant to fit to 32 bits) -- that way no overflow would happen, and even if the accuracy of the final model could be smaller, I think the result would not be noticable (given that gammas are sum of all alphas during training).

I am running the experiments on the dataset from the original report and will probably implement the rescaling.

Also, tagger module will be changed for 2.0, so this will go away.

**Comment by foxik** [comment] 2019-11-24 18:02
I tried to run the command 

> ```
> OPTIONS="models=1;run=2;use_lemma=0;provide_lemma=0;
>                   use_xpostag=0;provide_xpostag=0;use_feats=0;
>                   provide_feats=0;iterations=20"
> 
> udpipe --train --tokenizer=none --tagger=$OPTIONS --parser=none
>        --heldout=macmorpho-v1-dev-keep-pcp.conllu model.output
>        macmorpho-v1-train-keep-pcp.conllu
> ```

with both official UDPipe 1.2 and current master, but it did not fail.

@svetlana21, if you want me to try to debug the problem (or implement the rescaling), I will need data where it fails (ideally sooner than after a day of training ;-)

**Comment by foxik** [comment] 2020-06-29 11:22
Closing, but reopen if needed.

**Closed by foxik** 2020-06-29 11:22 UTC
