### ISSUE TITLE
congratulations on udpipe-future

### ISSUE THREAD

**Issue by jwijffels** [ufal/udpipe#74] opened 2018-07-30 12:38 UTC
My congratulations on your results with UDPipe-Future!
I'm just putting this issue here to see on what are your plans (if any) to convert the UDPipe-Future Python code in C++ format to incorporate it into ufal/udpipe. This all with a number of elements in mind

- to see how this will impact the R package which I created
- to see if there are other C++ dependencies involved
- to see how it would be possible to train new models alongside the new features of UDPipe-Future
- to see how I could retain the current documentation if you plan to change the ufal website of UDPipe and the new UDPipe-Future implementations would make the old version absolete

I would be happy to test out if needed.

**Comment by foxik** [comment] 2018-07-30 13:37
Thanks!

I am on vacation, will respond in more detail in ~2-3 weeks. In short, we would like to release UDPipe 2.0 (based on UDPipe-Future) with UD 2.3, i.e., 15 Nov. It will be still C++, but it will require one dynamic library (TensorFlow). The distribution of the library is yet unknown (i.e., if we just use the official URLs, or mirror selected versions, or even compile the versions by ourselves). In any case, the library will be used only for the models which require them, so the current models will continue to work without any dependencies. The URL will stay the same.

**Comment by jwijffels** [comment] 2018-07-30 13:44
thanks for the feedback. enjoy your holidays!

**Comment by msklvsk** [comment] 2018-10-02 16:59
I just want to acknowledge how usable UDPipe is compared to other shared task winners. Stanford and Harbin aren’t production-ready. You have to tokenize with UDPipe first, then pipe CONLL-U to their tagger, then pipe again through their parser, and then pipe back to UDPipe for lemmas. They have no http server built in, and (even with a custom server) they spend seconds to initialize for each chunk you feed them. Not to mention they consume twice the RAM because models don’t share embeddings. If UDPipe-Future will keep the same interface and in-process pipeline — that would be a huge step for the industry.

**Comment by danielhers** [comment] 2018-11-18 06:52
Hi @foxik, just wondering if there is an updated estimate on the UDPipe 2.0 release date. Thanks!

**Comment by foxik** [comment] 2018-11-25 08:30
The current estimate is still several weeks. We have the models ready, but bundling Tensorflow as a backend requires solving several technical issues, and I am doing a lot of teaching this semester.

**Comment by jwijffels** [comment] 2018-11-25 12:46
Looking forward to it - this is a great course by the way: https://github.com/ufal/npfl117 many thanks for sharing this!

**Comment by foxik** [comment] 2018-11-26 15:11
Thanks! If you like it, you can look at http://ufal.mff.cuni.cz/courses/npfl114 (and the Github repository of it), there we even have recordings of the lectures and many assignments :-)

**Comment by jwijffels** [comment] 2018-11-27 08:21
@foxik Many thanks for the links.

**Comment by msklvsk** [comment] 2018-12-14 22:00
Quick question: As written in the shared task [paper](http://universaldependencies.org/conll18/proceedings/pdf/K18-2020.pdf), UDPipe 2.0 will have the same tokenization/segmentation as 1.2? No point to delay tokenizing-deduping a huge corpus?

**Comment by foxik** [comment] 2018-12-16 11:48
The UDPipe 2.0 models for UD 2.3 will have the same tokenization/segmentation as the UD 2.3 models for UDPipe 1.2 released at https://lindat.mff.cuni.cz/repository/xmlui/handle/11234/1-2898. So you can use that now and wait for the better models :-)

BTW, in the planned UDPipe 3.0 (yes, I know 2.0 is not out yet) we will have better segmentation/tokenization modules, but we are talking about May (UD 2.4 release).

**Comment by jowagner** [comment] 2019-01-11 17:32
Link to the prototype: https://github.com/CoNLL-UD-2018/UDPipe-Future

**Comment by jwijffels** [comment] 2019-02-19 10:43
Hi @foxik, I have some time in the coming 2 months to integrate possible changes in the R interface. Any plans for the UDPipe 2.0 release which I can expect in the coming weeks?

**Comment by foxik** [comment] 2019-02-23 20:05
Hi, unfortunately, my plans with UDPipe 2.0 are still unrealized. A combination of health and a lot of teaching & students have taken all my time. I am still trying to do it as soon as possible, but now in the time of conferences and shared tasks I cannot really tell when I will get to it. Sorry.

**Comment by jwijffels** [comment] 2019-02-25 11:00
Hi @foxik. Good to hear that you are still planning to incorporate it - either sooner or later whichever suits you best!

**Comment by jwijffels** [comment] 2019-04-04 12:16
A link for UDPipe 2.1 ;)? https://128.84.21.199/pdf/1904.02099.pdf

**Comment by foxik** [comment] 2019-04-04 19:16
:-) That is written by a student of mine... (but all results are his own, I am just watching from the distance what is happening :-)

**Comment by jowagner** [comment] 2019-04-05 08:09
With domain name: https://arxiv.org/abs/1904.02099 and note that an update with proper literature review will follow shortly: https://twitter.com/hyperparticle/status/1113845007901814785

**Comment by jwijffels** [comment] 2019-08-20 09:58
Really nice work you did (https://arxiv.org/pdf/1908.06931.pdf) on integrating BERT, predicting each morphological feature & on merging corpora of the same language! 
I already wondered what this BERT integration would give. Thanks!

**Comment by foxik** [comment] 2019-08-20 10:59
Thanks! I will be submitting another paper today, this time evaluating BERT also on dependency parsing :-)

**Comment by jwijffels** [comment] 2019-08-20 11:13
Looking forward to see that one also appearing. Where will we be able to find this?

**Comment by foxik** [comment] 2019-08-20 12:01
arXiv again. It got rejected from EMNLP, but I think it needs to be published soon.

**Comment by jwijffels** [comment] 2019-08-21 20:18
Found it https://arxiv.org/pdf/1908.07448.pdf.
These are tremendously impressive results :)

**Comment by EmilStenstrom** [comment] 2019-11-23 15:23
Is there any way for UDPipe users to help out sponsor continued work on UDPipe?

**Comment by foxik** [comment] 2019-11-23 17:44
Sorry, I am spread thin by by taking a lot of other responsibilities (since I want to stay at the university, I took up teaching and master and phd students).

The UDPipe is however still among my responsibilities and being worked on -- the problem is that we are rewriting nearly everything to use C++ TensorFlow library as a backend, and it takes some time.

I see no easy way of contributing until we have the basic infrastructure in place, sorry...

As a sidenotes, the UDPipe 2 is expected to support arbitrary NLP operations (not only tokenizing, tagging and parsing), and we have NER, NE linking, GEC and semantic parsing prototypes :-)

**Comment by EmilStenstrom** [comment] 2019-11-23 18:03
Supporting NER, NE linking sounds fantastic :) I'm so looking forward to using the new version in my (work and hobby) projects!

**Comment by ArijRB** [comment] 2020-10-14 13:32
Hey, 
Thank you for sharing your contributions. Any update about on the UDPipe 2.0 release date. Thanks!
@foxik

**Comment by foxik** [comment] 2020-10-15 13:18
As mentioned at http://ufal.mff.cuni.cz/udpipe/2 , the UDPipe 2 models are already available in our REST server; the release of the models themselves and the UDPipe 2 should happen in the following weeks.

As http://ufal.mff.cuni.cz/udpipe describes, UDPipe 2 is just a Python prototype (to get the models to the public); the C++ version has now been designated as UDPipe 3 and it is ... (surprise, surprise) ... still being worked on.

**Comment by ArijRB** [comment] 2020-10-15 13:23
@foxik 
> As mentioned at http://ufal.mff.cuni.cz/udpipe/2 , the UDPipe 2 models are already available in our REST server; the release of the models themselves and the UDPipe 2 should happen in the following weeks.
> Thank you for your response. I am intersted in training UDPipe 2 on new data.
> As http://ufal.mff.cuni.cz/udpipe describes, UDPipe 2 is just a Python prototype (to get the models to the public); the C++ version has now been designated as UDPipe 3 and it is ... (surprise, surprise) ... still being worked on.
Cool, thanks

**Comment by foxik** [comment] 2023-02-16 09:11
Closing, as future development will move from UDPipe to LinPipe.

**Closed by foxik** 2023-02-16 09:11 UTC

**Comment by jowagner** [comment] 2023-02-17 19:59
https://github.com/ufal/linpipe
